### ISSUE TITLE
Fix width of buttons in WelcomeFragment

### ISSUE THREAD

**Issue by serbelga** [Bacotatech/BacotaApp_Android#4]
Buttons are cut when App is launched on some screens
![screenshot_20200809-211535.png](https://user-images.githubusercontent.com/26246782/89740129-7c0e3480-da86-11ea-9d17-b146fa9490f7.png)

**Comment by serbelga** [comment]
Resolved in

**Comment by tonilopezmr** [comment]
I can confirm 👍
